name: ci

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        platform: [
          ubuntu-latest,
          # macos-latest, 
          # windows-latest
        ]
        python-version: [3.11]
    runs-on: ${{matrix.platform}}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - id: cache-dependencies
        name: Cache dependencies
        uses: actions/cache@v2.1.7
        with:
          path: ${{ github.workspace }}/.venv
          key: ${{ matrix.platform }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ matrix.platform }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --with=dev
      - name: Lint with Ruff
        # continue-on-error: true
        run: ruff check .
      - name: Lint with Ruff
        continue-on-error: true
        run: ruff format .
      - name: Type check with mypy
        continue-on-error: true
        run: mypy .
      - name: Test with pytest
        continue-on-error: true
        run: pytest .

