name: ci

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          environment-name: aia-tool-craft
          cache-environment: true
      - name: Install dependencies
        run: python -m poetry install --with=dev
      - name: Lint with Ruff
        continue-on-error: true
        run: ruff check .
      - name: Lint with Ruff
        continue-on-error: true
        run: ruff format .
      - name: Type check with mypy
        continue-on-error: true
        run: mypy .
      - name: Test with pytest
        continue-on-error: true
        run: pytest .

